custom: [
  "bitcoin:1TTCLqLHSNegudfS7Ub7dUEGxUurGs8uH", 
  "litecoin:LQLTTCLUG9g7EfnpanwPH5MFjr7jdQRzfs", 
  "dogecoin:DTTCLQLeCGDmKmwyy2Nn2SYgbLAyE662ua", 
  "ethereum:0x11C1014fA416c585DE0BA41900056fB9407D57a2"
]
